### PR TITLE
Background.

### PR DESCRIPTION
**Pull request by larsbrinkhoff**
I'm not sure if this is helpful or not?

@eswenson1, @Alexey-Slyusar, @everyfan, I'm writing this so I can help you learn some git tricks.  What do you think?

### CODE REVIEW

**Comment by eswenson1** [comment]
Go for it!

**Comment by Alexey-Slyusar** [comment]
It is just fantastic idea!
Lars, thank you very much!

ср, 23 янв. 2019 г. в 10:07, Eric Swenson <notifications@github.com>:

**Comment by larsbrinkhoff** [comment]
Thanks.  I mean this ["background" information](https://github.com/larsbrinkhoff/fearless-git/pull/1/commits/13b9c3b698979e773377c7b11bb0499a0698c17a).  Is it helpful to you?

I'll cover these subjects:  
https://github.com/larsbrinkhoff/fearless-git/issues

**Comment by Alexey-Slyusar** [comment]
"Background information" is interesting and lead to better understanding, I
think. The information is helpful for me.

ср, 23 янв. 2019 г. в 10:35, Lars Brinkhoff <notifications@github.com>:

**Comment by popeyeotaku** [comment]
Great idea! (I sure don't know what I'm doing XD)

**Pull request merged**
